### ISSUE TITLE
Should probably include the line-directive tool

### ISSUE THREAD

**Issue by dabrahams** [jph00/gyb#2]
At least, if you want people to use this with swift

**Comment by jph00** [comment]
Done.

**Comment by jph00** [comment]
BTW I don't actually use that file or know what it's for (googling gave me a general sense, but couldn't find details) so do let me know if I've made any mistakes in how it's packaged. I'm guessing it's something to do with Xcode? (I'm on Linux).

In order to support standard module usage (required for cross-platform binary installation) I had to remove the '-' and append '.py', but the actual script has the original name.

**Comment by dabrahams** [comment]
Nothing to do with Xcode.  In fact, I have been unable to properly integrate it with Xcode, but the Swift project itself, which builds with CMake/Ninja, does use it.  

`#sourceLocation` is a directive used by tools like the compiler to adjust where it points when you have a compilation error, or by the debugger to determine what source you see.  `#sourceLocation` corresponds to `#line` in C/C++ and is inserted by code generators like Lex/Flex/Yacc/Bison so that you deal with the actual code you wrote and not the generated result.  This is maybe not so compelling for debugging but for dealing with errors in the Swift generated by your gyb source it's absolutely critical that your tools take you to the right line in your `.gyb` file rather than in generated `.swift` file.  Heh, I forget how many people don't use tools that jump to the error line automatically, but if you build with Emacs' `M-x compile` command, for example, that's what you get.  If you *don't* have such a tool, manually double-indirecting through the generated code is hell, but at least it's *possible* if we leave `#sourceLocation` information behind.

But Swift's `#sourceLocation` directive is broken for the purposes of freeform code generation like what we do with gyb because it can only appear between grammatically-complete decls and statements (or something like that).  So instead of issuing `#sourceLocation`, gyb inserts `// ###sourceLocation` comments (by default—it's tunable).  The `lineDirective` tool is there  to remap file and line information in the output of your swift compiler (or whatever tool you are using to process generated source—gyb is not swift-specific) so that the error points to the right place in the `.gyb` source.  You invoke it as follows:

```
line-directive <generated-sources> -- <compilation command>
```

e.g., if you have `foo.swift.gyb`, `bar.swift.gyb`, and `baz.swift`, instead of

```
gyb foo.swift.gyb -o foo.swift
gyb bar.swift.gyb -o bar.swift
swiftc foo.swift bar.swift baz.swift
```

You do this:

```
gyb foo.swift.gyb -o foo.swift
gyb bar.swift.gyb -o bar.swift
line-directive foo.swift bar.swift -- swiftc foo.swift bar.swift baz.swift
```

HTH.

**Comment by jph00** [comment]
That's awesomely useful info - thanks! It's been bothering me that the
reported line numbers don't match my input file, so this is just what
I need. :)

**Comment by dabrahams** [comment]
Yeah, most people don't understand it and turn off line directive injection when they use gyb. If you could find a way to put some of this info in your package, that'd be great.

**Comment by jph00** [comment]
Do you mind if I copy your info (with credit) directly into the readme?

**Comment by dabrahams** [comment]
Not at all, but please see https://github.com/apple/swift/pull/21653 and https://github.com/apple/swift/pull/21654, the latter of which has a refined version of that text.

**Comment by jph00** [comment]
Perfect - added to the readme now. :)
